# Generated by Django 3.0.4 on 2020-03-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car_size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_size', models.CharField(max_length=10, verbose_name='차량종류')),
            ],
        ),
        migrations.CreateModel(
            name='DriverInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_no', models.CharField(max_length=10, verbose_name='차량번호')),
                ('phone_number_field', models.CharField(max_length=15, verbose_name='전화번호')),
                ('car_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='support_shipment.car_size')),
            ],
        ),
        migrations.CreateModel(
            name='Support_Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_type', models.CharField(max_length=20, verbose_name='규격')),
                ('support_length', models.IntegerField(verbose_name='길이')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment_orderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateField(auto_now=True, verbose_name='접수일')),
                ('ERP_Number', models.CharField(max_length=30, verbose_name='공사번호')),
                ('salesman_name', models.CharField(max_length=10, verbose_name='영업사원')),
                ('company_name', models.CharField(max_length=20, verbose_name='업체명')),
                ('location_name', models.CharField(max_length=30, verbose_name='현장명')),
                ('district_name', models.CharField(max_length=10, verbose_name='동')),
                ('is_it_head', models.BooleanField(default=False, verbose_name='헤드유무')),
                ('quantity', models.IntegerField(default=0, verbose_name='수량')),
                ('requst_arrival_option', models.CharField(default='당일착', max_length=10, verbose_name='도착도')),
                ('other_notes', models.TextField(verbose_name='기타사항')),
                ('location_info', models.CharField(max_length=20, verbose_name='지역')),
                ('support_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_order_type', to='support_shipment.Support_Spec')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateField(auto_now=True, verbose_name='접수일')),
                ('order_status', models.CharField(default='대기', max_length=20, verbose_name='오더상태')),
                ('order_no', models.IntegerField(blank=True, null=True, verbose_name='배차번호')),
                ('quantity', models.IntegerField(default=0, verbose_name='수량')),
                ('out_time', models.DateTimeField(auto_now_add=True, verbose_name='변동시간')),
                ('driver_inormation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support_shipment.DriverInformation')),
                ('support_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_type', to='support_shipment.Support_Spec')),
            ],
        ),
    ]
