# Generated by Django 3.0.4 on 2020-03-13 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support_shipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20, verbose_name='업체명')),
                ('location_name', models.CharField(max_length=30, verbose_name='현장명')),
                ('district_name', models.CharField(max_length=10, verbose_name='동')),
            ],
        ),
        migrations.RemoveField(
            model_name='shipment_ordermodel',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='shipment_ordermodel',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='shipment_ordermodel',
            name='location_name',
        ),
        migrations.AddField(
            model_name='shipment_ordermodel',
            name='Location_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='support_shipment.LocationModel'),
            preserve_default=False,
        ),
    ]
