# Generated by Django 3.0.4 on 2020-03-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_shipment', '0002_auto_20200313_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment_ordermodel',
            name='ERP_Number',
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='ERP_Number',
            field=models.CharField(default=1, max_length=30, verbose_name='공사번호'),
            preserve_default=False,
        ),
    ]
