# Generated by Django 3.0.4 on 2020-03-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_shipment', '0003_auto_20200313_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment_ordermodel',
            name='other_notes',
            field=models.TextField(blank=True, null=True, verbose_name='기타사항'),
        ),
    ]
