# Generated by Django 3.0.4 on 2020-03-13 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support_shipment', '0005_auto_20200313_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderspecification',
            name='driver_inormation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support_shipment.DriverInformation'),
        ),
        migrations.AlterField(
            model_name='orderspecification',
            name='submit_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 13, 22, 23, 48, 548836), verbose_name='접수일'),
        ),
    ]
