# Generated by Django 3.0.4 on 2020-03-13 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('support_shipment', '0006_auto_20200313_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderspecification',
            name='submit_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='접수일'),
        ),
    ]
